
project_id = "igfpasvqbjczyohitymc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions.chat]
verify_jwt = true

[functions.format-citation]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.create-paypal-checkout]
verify_jwt = true

[functions.paypal-webhook]
verify_jwt = false

