// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igfpasvqbjczyohitymc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnZnBhc3ZxYmpjenlvaGl0eW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxODc1MTMsImV4cCI6MjA1NTc2MzUxM30.OCTAnf1Otn1XYa1E3PY2yZz5vCjmzWDtDUHkA8qA1O4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);